### ISSUE TITLE
Problem of building on cloudflare and netlify

### ISSUE THREAD

**Issue by crowscript** [thecodercoder/gulp-browsersync#2]
I don't know is this only problem for me, but I got some errors when building on cloudflare or netlify.
Did anyone else try this build on these servers?

**Comment by thecodercoder** [comment]
What error message did you get? If you're building on a production server then you probably don't want to run Browsersync or the Gulp watch tasks, as those will continue running and watching files for when you're in development. I'm not certain this is the cause however without knowing what error you're seeing.

**Comment by crowscript** [comment]
Now is working build on cloudflare.
On netlify is still some errors, it is long list, this is beggining 
`12:24:50 PM: npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
12:27:13 PM: npm ERR! code 1
12:27:13 PM: npm ERR! path /opt/build/repo/node_modules/node-sass
12:27:13 PM: npm ERR! command failed
12:27:13 PM: npm ERR! command sh -c node scripts/build.js
12:27:13 PM: npm ERR! Building: /opt/buildhome/.nvm/versions/node/v16.10.0/bin/node /opt/build/repo/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=`

I upgraded all, but still the same.
But no worry, it is working on cloudflare, thanks a lot for answer.
